import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import Provider from "./_trpc/Provider";

import { NavBar } from './components/NavBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BayBoyz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <ClerkProvider>
            <Provider>
              <main className="relative flex flex-col min-h-screen">
                  <section>
                    <NavBar />
                  </section>
                  <div className="flex-grow flex-1">
                    {children}
                  </div>
              </main>
            </Provider>
          </ClerkProvider>
        </body>
      </html>
      
  );
}
